"""empty message

Revision ID: 698b35f7fc65
Revises: cc6c8f2dea52
Create Date: 2021-04-02 14:18:59.584483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698b35f7fc65'
down_revision = 'cc6c8f2dea52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
